### ISSUE TITLE
Add collaborator to pypi

### ISSUE THREAD

**Issue by axiak** [bancek/fabric-threadsafe#1]
Hey bancek,

I forked the repository at https://github.com/HubSpot/fabric-threadsafe and was wondering if I could get access to deploy to pypi. I have to update the code to support the latest fabric and we'd like to maintain the code to match the fabric versions (we'll probably have a git tag for each fabric version that works).

**Comment by bancek** [comment]
Hi

I would like to keep maintaining this project.

Please issue a pull request so I can merge changes and release a new version.
